### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by sherming4444** [Saren-Arterius/hkgpx#1]
root@mails:~/hkgpx# node server.js

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/root/hkgpx/node_modules/restify/node_modules/csv/node_modules/csv-generate/lib/index.js:95:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/root/hkgpx/node_modules/restify/node_modules/csv/lib/index.js:4:12)
    at Module._compile (module.js:449:26)

How can i fix this?

**Comment by Saren-Arterius** [comment]
Maybe restify does not support your node.js version
Currently I am using nodejs 0.12.4 for all of my public servers except rhcloud (openshift) one, it's using node 0.10

**Comment by sherming4444** [comment]
I updated to 0.12.5, but have the other error.

root@mails:~/hkgpx# node server.js
/root/hkgpx/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /root/hkgpx/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node: undefined symbol: _ZN2v82V817IsGlobalNearDeathEPPNS_8internal6ObjectE
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/root/hkgpx/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/root/hkgpx/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by Saren-Arterius** [comment]
I can't replicate this issue, I think it's your system library's issue.
What linux distro and version you are currently using?

**Comment by sherming4444** [comment]
Ubuntu 14 32bit
What linux distro you are using?

**Comment by Saren-Arterius** [comment]
hkgpx has been tested in Archlinux, heroku dynos and openshift system.
I am currently testing it in ubuntu14.04 _virtualbox_

**Comment by Saren-Arterius** [comment]
Updated install guide for ubuntu 14, please try

**Comment by sherming4444** [comment]
HKGPX listening at http://0.0.0.0:8888
Is it right?
